### ISSUE TITLE
side margin is too small

### ISSUE THREAD

**Issue by yegor256** [ammaratef45/zold-flutter-client#109] opened 2019-05-28 11:30 UTC
We need to make it larger, at least twice as big as it is now. The content stays now too close to the borders of the screen. Make the margin bigger.

**Comment by 0crat** [comment] 2019-05-28 11:30
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-05-28 11:30
@yegor256[/z](https://www.0crat.com/u/yegor256) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2019-05-28 11:38
Job [#109](https://github.com/ammaratef45/zold-flutter-client/issues/109) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-06-01 11:41
The job [#109](https://github.com/ammaratef45/zold-flutter-client/issues/109) assigned to @amorenew[/z](https://www.0crat.com/u/amorenew), here is [why](https://www.0crat.com/footprint/CGC59KB9B/9377e6f1-ab33-45fb-9c5f-29cea1ee7152); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-06-06 11:39
@amorenew[/z](https://www.0crat.com/u/amorenew) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment] 2019-06-09 06:57
@amorenew I think this should be closed as the new design is implemented, right?

**Comment by amorenew** [comment] 2019-06-09 07:01
@ammaratef45 Yes I think

**Closed as completed** 2019-06-09 07:02 UTC
Labels: bug

**Comment by 0crat** [comment] 2019-06-09 07:06
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.2' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.47.5](https://github.com/zerocracy/farm): CID: [efc1d254-6965-42a6-bf30-4e3abe75628b](https://www.0crat.com/footprint/CGC59KB9B/efc1d254-6965-42a6-bf30-4e3abe75628b), Type: "Job milestoned"

**Comment by 0crat** [comment] 2019-06-09 07:19
Job [#109](https://github.com/ammaratef45/zold-flutter-client/issues/109) is not in the agenda of @amorenew[/z](https://www.0crat.com/u/amorenew), can't inspect

**Comment by 0crat** [comment] 2019-06-09 07:19
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @amorenew[/z](https://www.0crat.com/u/amorenew), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-06-09 07:19
The job [#109](https://github.com/ammaratef45/zold-flutter-client/issues/109) is now out of scope

**Comment by sereshqua** [comment] 2019-06-09 07:33
@amorenew 

quality is bad when the job is closed without a solution provided.

**Comment by ammaratef45** [comment] 2019-06-09 07:35
@sereshqua you didn't mention 0crat

**Comment by sereshqua** [comment] 2019-06-09 07:37
@ammaratef45 i know, I just want to warn @amorenew about it before giving a verdict 

> When you find any rules violation, ask job performer to confirm that your complaints are understood, and he/she will try to avoid those mistakes in the future. Until you get a confirmation, don’t give any quality mark; don’t wait for more than five days though.

**Comment by ammaratef45** [comment] 2019-06-09 07:39
@sereshqua Ah, okay.

**Comment by amorenew** [comment] 2019-06-09 10:15
@sereshqua I confirm it is a duplicate issue
so How to tell 0crat that the issue is a duplicate?

**Comment by ammaratef45** [comment] 2019-06-09 10:19
@amorenew It's my responsibility to get it out of scope :smile: 
Sorry!
/cc @sereshqua

**Comment by sereshqua** [comment] 2019-06-09 10:48
@ammaratef45 @amorenew thanks fro your comments

**Comment by sereshqua** [comment] 2019-06-09 10:49
@0crat quality bad

**Comment by 0crat** [comment] 2019-06-09 10:50
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2019-06-09 10:56
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
