### ISSUE TITLE
Blank white screen on Android

### ISSUE THREAD

**Issue by g4s8** [ammaratef45/zold-flutter-client#131] opened 2019-09-23 12:40 UTC
**Describe the bug**
Android app version `1.3.1` it shows me blank white screen forever on start.

**To Reproduce**
1. Install `1.3.1` version
2. Launch it with Google-play "open" button or from applications 

**Expected behavior**
App shows login page

**Screenshots**

**Phone (please complete the following information):**
Device: Nexus5 with Android 6.0.1

**Additional context**
Tried to kill it with "force stop", tried to remove all data, tried to remove and install again - didn't help.

**Comment by 0crat** [comment] 2019-09-23 12:40
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-09-23 12:40
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CGC59KB9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2019-09-24 09:17
Job [#131](https://github.com/ammaratef45/zold-flutter-client/issues/131) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-09-24 09:28
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment] 2019-09-24 09:30
The job [#131](https://github.com/ammaratef45/zold-flutter-client/issues/131) assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/CGC59KB9B/e862f216-48ce-4264-a678-0514edd454c8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-09-27 18:29
The job [#131](https://github.com/ammaratef45/zold-flutter-client/issues/131) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CGC59KB9B/abe43e88-8799-4f69-8173-8d883def97e5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-09-27 18:30
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment] 2019-09-28 03:08
@g4s8 
The problem is related to this issue anish-adm/trust_fall#6.

No need to check for location mocking so I've listed the trust checks myself leaving the location mocking check and It worked.
 
Another problem is that It's not deployable because google play isn't accepting 32-bit builds anymore.

`Publishing failed :| Failed to publish: Release is not compliant with the Play 64-bit requirement.`
I've opened #132 and you can follow it (The app will be deployed once it's solved)

Thanks for reporting this.

**Closed as completed by ammaratef45** 2019-09-28 03:08 UTC
Labels: potential-bug

**Comment by 0crat** [comment] 2019-09-28 03:26
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment] 2019-09-28 03:30
The job [#131](https://github.com/ammaratef45/zold-flutter-client/issues/131) is now out of scope

**Comment by 0crat** [comment] 2019-09-28 03:30
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d1633530-cab7-409b-88c9-002bbce22b6f, thread: pool-49-thread-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..174..acy.com/0.66.1/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.49.14](https://github.com/zerocracy/farm): CID: [6f73775e-255b-4192-944d-35e79d944a36](https://www.0crat.com/footprint/CGC59KB9B/6f73775e-255b-4192-944d-35e79d944a36), Type: "Transfer shares"

**Comment by 0crat** [comment] 2019-09-28 03:32
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by g4s8** [comment] 2019-09-28 08:56
@ammaratef45 thanks! BTW, we do you need location permissions? It seems unrelated to wallet functionality.

**Comment by ammaratef45** [comment] 2019-09-28 10:58
@g4s8 I've changed it back, I was trying to stop the error without editing the `trust` checking part
